# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
latex: false
cache:
  packages: true
  
before_install:
- |
  # 1. Install TinyTex manually if not already in cache
  # Travis creates $HOME/.TinyTex if nonexistent, so we check bin subdir
  if [ ! -d $HOME/.TinyTex/bin ]; then
    Rscript -e "tinytex::install_tinytex()"
  fi

script:
  - Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::gitbook")'
  - Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::epub_book")'
  - Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::pdf_book")'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $INTRO_DA
  keep_history: true
  on:
    branch: master
  local_dir: _book
  target_branch: gh-pages